version: 2.1

jobs:

  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01

    working_directory: ~/stomp.py
    steps:


      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            uname -m
            sudo apt-get install python3 && sudo apt-get install python3-pip
            python3 --version
            pip3 install --upgrade virtualenv --progress-bar off
            python3 -m venv venv || virtualenv venv && . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install poetry
            poetry install
            pytest
            
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/stomp.py
    steps:

      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            uname -m
            sudo apt-get install python3 && sudo apt-get install python3-pip
            python3 --version
            pip3 install --upgrade virtualenv --progress-bar off
            python3 -m venv venv || virtualenv venv && . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install poetry
            poetry install
            pytest
                    
      

workflows:
  version: 2
  python3.8:
    jobs:

      - build-medium-amd64
      - build-medium-arm64
